### ISSUE TITLE
setting isTransitive = true pulls sentry 6.28.0 into my app which is does not support Android 15 16KB page size causing crash 

### ISSUE THREAD

**Issue by daniel-waiguru** [vbmobile/ComposeSampleApp#1]
Hello
Vision box dependency requires is `isTransitive` to be set to true, which pulls in sentry android 6.28.0 which does not currently support Android 15 16KB page size causing crash on 16KB page size environment

**Comment by daniel-waiguru** [comment]
@JoseRosarioVB  @vbmobile

**Comment by vbmobile** [comment]
Hello
What version of the SDK are you using? In version 7.2.2 we removed sentry dependency.

**Comment by daniel-waiguru** [comment]
currently using version 7.2.1

**Comment by vbmobile** [comment]
Please use the latest version available in that major: 7.3.1
https://vbmobile.github.io/mobile-id-documentation/latest/ReleaseNotes/ReleaseNotes_Android.html
There shouldn't be any required changes when increasing the version and you can check the release notes in the link above.
Let me know if you need anything else.
